#
# Dedicated index for Splunk documentation pages.
#
[splunk_docs]
homePath   = $SPLUNK_DB/splunk_docs/db
coldPath   = $SPLUNK_DB/splunk_docs/colddb
thawedPath = $SPLUNK_DB/splunk_docs/thaweddb
maxTotalDataSizeMB = 5120
frozenTimePeriodInSecs = 315360000
